select distinct top(1) 



selcet INSTREG.STATION,

INSTMOD.MAKE,

INSTMOD.MODEL,

INSTREG.SERIAL,

INSTSER.DATE,

INSTSER.SERVICETYP,

INSTSER.FAULT,

INSTSER.DESCR,

INSTSER.SERVICEDUE,

INSTREG.PURORDER,

INSTCAL.RECALDUE,

INSTREG.PURDATE,

INSTREG.RETIRE,

INSTHIST.DATEIN

from INSTREG, INSTMOD

where INSTMOD.MODEL=INSTREG.MODEL and INSTMOD.MODEL=INSTREG.MODEL and INSTMOD.MODEL=INSTCAL.MAODEL and INSTMOD.MODEL=INSTHIST.MODEL

group by INSTMOD.MAKE, INSTMOD.MODEL, INSTMOD.DESCR

order by INSTCAL.RECALDUE,INSTHIST.DATEIN,INSTSER.SERVICEDUE DESC



order by INSTCAL.RECALDUE,INSTHIST.DATEIN,INSTSER.SERVICEDUE DESC



order by INSTMOD.MAKE, INSTMOD.MODEL, INSTMOD.DESCR





select INSTMOD.MAKE, INSTMOD.MODEL, INSTMOD.DESCR, 

count(INSTREG.RESIDVAL) as Count,

sum(INSTREG.COST) as Cost,

sum(INSTREG.RESIDVAL) as Residual, 

sum(INSTREG.CURRYRDEP) as Deprec

from INSTREG,INSTMOD

where INSTMOD.MAKE=INSTREG.MAKE and INSTMOD.MODEL=INSTREG.MODEL

group by INSTMOD.MAKE, INSTMOD.MODEL, INSTMOD.DESCR

order by INSTMOD.MAKE, INSTMOD.MODEL, INSTMOD.DESCR



